### ISSUE TITLE
dev folder already exists

### ISSUE THREAD

**Issue by king-ton** [Corilus/sftp#4]
Hi Corilus,

I currently have the problem that the container throw an error after it was redownloaded.
I have mount the user folder as a volume. The following line throws an error because the folder already exists: https://github.com/Corilus/sftp/blob/4846165fb7e0ffc9d7abe9a91721b00379e38ce7/files/create-sftp-user#L108

It is possible to add a check that the folder only be created if it not exists? Thank you! :)

**Comment by ryanwinchester** [comment]
Maybe this
```bash
if [ ! -d "/home/$user/dev" ]; then
    mkdir -m2755 "/home/$user/dev" 
fi
```

**Comment by dwagelaar** [comment]
Created https://github.com/Corilus/sftp/pull/7

**Comment by dwagelaar** [comment]
Merged https://github.com/Corilus/sftp/pull/7
